// the data for South Sudan (SSD), Palestinian Territories (PSE) and Kosovo (XK)
// are dodgy so I've omitted them
export const countries = ["AFG", "ALB", "AGO", "ARM", "AZE", "BGD", "BLZ",
    "BEN", "BTN", "BOL", "BIH", "BFA", "BDI", "KHM", "CMR", "CPV", "CAF", "TCD",
    "CHN", "COM", "CIV", "CUB", "DJI", "PRK", "COD", "EGY", "SLV", "ERI", "ETH",
    "FJI", "GMB", "GEO", "GHA", "GTM", "GIN", "GNB", "GUY", "HTI", "HND", "IND",
    "IDN", "IRQ", "KEN", "KIR", /*"XK",*/ "KGZ", "LSO", "LBR", "MDG", "MWI",
    "MLI", "MHL", "MRT", "FSM", "MDA", "MNG", "MAR", "MOZ", "MMR", "NPL", "NIC",
    "NER", "NGA", "PAK", /*"PSE",*/ "PNG", "PRY", "LAO", "PHL", "COG", "RWA",
    "WSM", "STP", "SEN", "SLE", "SLB", "SOM", /*"SSD",*/ "LKA", "SDN", "SWZ",
    "SYR", "TJK", "TZA", "TLS", "TGO", "TON", "TKM", "TUV", "UGA", "UKR", "UZB",
    "VUT", "VNM", "YEM", "ZMB", "ZWE"];

export const diseases = ["HepB", "Hib", "HPV", "JE", "Measles", "MenA", "PCV",
    "Rota", "Rubella", "YF"];

export const diseaseVaccines = {
    "HepB":["HepB","HepB_BD"],
    "Hib":["Hib3"],"HPV":["HPV"],
    "JE":["JE"],
    "Measles":["MCV1","MCV2","Measles"],
    "MenA":["MenA"],
    "PCV":["PCV3"],
    "Rota":["Rota"],
    "Rubella":["Rubella"],
    "YF":["YF"]
}

export const activityTypes = ["routine", "campaign", "combined"];

export const plottingVariables = ["year", "country", "continent", "region",
    "cofinance_status_2018", "activity_type", "disease", "vaccine", "touchstone", "support_type"];

export const touchstones = ["201710gavi", "201710gavi-201810gavi", "201510gavi",
                            "201310gavi-201810gavi", "201310gavi",
                            "201310gavi-201403gavi", "201510gavi-201810gavi",
                            "201210gavi-201810gavi", "201210gavi-201303gavi"];

export const supportTypes = ["gavi", "other"];

export const countryDict = [
    {"country":"AFG","country_name":"Afghanistan"},
    {"country":"ALB","country_name":"Albania"},
    {"country":"AGO","country_name":"Angola"},
    {"country":"ARM","country_name":"Armenia"},
    {"country":"AZE","country_name":"Azerbaijan"},
    {"country":"BGD","country_name":"Bangladesh"},
    {"country":"BLZ","country_name":"Belize"},
    {"country":"BEN","country_name":"Benin"},
    {"country":"BTN","country_name":"Bhutan"},
    {"country":"BOL","country_name":"Bolivia, Plurinational State of"},
    {"country":"BIH","country_name":"Bosnia and Herzegovina"},
    {"country":"BFA","country_name":"Burkina Faso"},
    {"country":"BDI","country_name":"Burundi"},
    {"country":"CPV","country_name":"Cabo Verde"},
    {"country":"KHM","country_name":"Cambodia"},
    {"country":"CMR","country_name":"Cameroon"},
    {"country":"CAF","country_name":"Central African Republic"},
    {"country":"TCD","country_name":"Chad"},
    {"country":"CHN","country_name":"China"},
    {"country":"COM","country_name":"Comoros"},
    {"country":"COG","country_name":"Congo"},
    {"country":"COD","country_name":"Congo, the Democratic Republic of the"},
    {"country":"CIV","country_name":"Cote d'Ivoire"},
    {"country":"CUB","country_name":"Cuba"},
    {"country":"DJI","country_name":"Djibouti"},
    {"country":"EGY","country_name":"Egypt"},
    {"country":"SLV","country_name":"El Salvador"},
    {"country":"ERI","country_name":"Eritrea"},
    {"country":"ETH","country_name":"Ethiopia"},
    {"country":"FJI","country_name":"Fiji"},
    {"country":"GMB","country_name":"Gambia"},
    {"country":"GEO","country_name":"Georgia"},
    {"country":"GHA","country_name":"Ghana"},
    {"country":"GTM","country_name":"Guatemala"},
    {"country":"GIN","country_name":"Guinea"},
    {"country":"GNB","country_name":"Guinea-Bissau"},
    {"country":"GUY","country_name":"Guyana"},
    {"country":"HTI","country_name":"Haiti"},
    {"country":"HND","country_name":"Honduras"},
    {"country":"IND","country_name":"India"},
    {"country":"IDN","country_name":"Indonesia"},
    {"country":"IRQ","country_name":"Iraq"},
    {"country":"KEN","country_name":"Kenya"},
    {"country":"KIR","country_name":"Kiribati"},
    {"country":"PRK","country_name":"Korea, Democratic People's Republic of"},
    {"country":"XK","country_name":"Kosovo"},
    {"country":"KGZ","country_name":"Kyrgyzstan"},
    {"country":"LAO","country_name":"Lao People's Democratic Republic"},
    {"country":"LSO","country_name":"Lesotho"},
    {"country":"LBR","country_name":"Liberia"},
    {"country":"MDG","country_name":"Madagascar"},
    {"country":"MWI","country_name":"Malawi"},
    {"country":"MLI","country_name":"Mali"},
    {"country":"MHL","country_name":"Marshall Islands"},
    {"country":"MRT","country_name":"Mauritania"},
    {"country":"FSM","country_name":"Micronesia, Federated States of"},
    {"country":"MDA","country_name":"Moldova, Republic of"},
    {"country":"MNG","country_name":"Mongolia"},
    {"country":"MAR","country_name":"Morocco"},
    {"country":"MOZ","country_name":"Mozambique"},
    {"country":"MMR","country_name":"Myanmar"},
    {"country":"NPL","country_name":"Nepal"},
    {"country":"NIC","country_name":"Nicaragua"},
    {"country":"NER","country_name":"Niger"},
    {"country":"NGA","country_name":"Nigeria"},
    {"country":"PAK","country_name":"Pakistan"},
    {"country":"PSE","country_name":"Palestine, State of"},
    {"country":"PNG","country_name":"Papua New Guinea"},
    {"country":"PRY","country_name":"Paraguay"},
    {"country":"PHL","country_name":"Philippines"},
    {"country":"RWA","country_name":"Rwanda"},
    {"country":"WSM","country_name":"Samoa"},
    {"country":"STP","country_name":"Sao Tome and Principe"},
    {"country":"SEN","country_name":"Senegal"},
    {"country":"SLE","country_name":"Sierra Leone"},
    {"country":"SLB","country_name":"Solomon Islands"},
    {"country":"SOM","country_name":"Somalia"},
    {"country":"SSD","country_name":"South Sudan"},
    {"country":"LKA","country_name":"Sri Lanka"},
    {"country":"SDN","country_name":"Sudan"},
    {"country":"SWZ","country_name":"Swaziland"},
    {"country":"SYR","country_name":"Syrian Arab Republic"},
    {"country":"TJK","country_name":"Tajikistan"},
    {"country":"TZA","country_name":"Tanzania, United Republic of"},
    {"country":"TLS","country_name":"Timor-Leste"},
    {"country":"TGO","country_name":"Togo"},
    {"country":"TON","country_name":"Tonga"},
    {"country":"TUN","country_name":"Tunisia"},
    {"country":"TKM","country_name":"Turkmenistan"},
    {"country":"TUV","country_name":"Tuvalu"},
    {"country":"UGA","country_name":"Uganda"},
    {"country":"UKR","country_name":"Ukraine"},
    {"country":"UZB","country_name":"Uzbekistan"},
    {"country":"VUT","country_name":"Vanuatu"},
    {"country":"VNM","country_name":"Viet Nam"},
    {"country":"YEM","country_name":"Yemen"},
    {"country":"ZMB","country_name":"Zambia"},
    {"country":"ZWE","country_name":"Zimbabwe"}
]
