#!/usr/bin/env python3
import json
import os


def save(data, filename):
    text = "const impactData={}".format(data)

    with open(filename, "w") as f:
        f.write(text)


def thin_array(text):
    text = text.rpartition('=')[2].lstrip()
    data = json.loads(text)
    print("Original row count: {}".format(len(data)))
    thinned = list(filter(lambda x: iterate(), data))
    print("Thinned row count: {}".format(len(thinned)))
    return json.dumps(thinned)


i = [0]


def iterate():
    i[0] = i[0]+1
    return i[0]%3 == 0


def read_lines(filename):
    with open(filename, "r") as f:
        return f.read()


if __name__ == "__main__":
    original = read_lines("data/impactData.js")
    save(thin_array(original), "data/test/impactData.js")
    print("Thinned data set saved to data/test/impactData.js")